#
#
#
services:
  
  APPNAME:
    image: image/image
    container_name: APPNAME
    hostname: APPNAME
    networks: ["proxy","socket","internal"]      
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
      - $MEDIA:$MEDIA
      - $USENET:$USENET
      - $TORRENTS:$TORRENTS
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
#     Theme.Park.dev {Requires linuxserver.io containers}       
#      TP_THEME: ${THEME} # change in global.env file for global theme changes
#      DOCKER_MODS: ghcr.io/gilbn/theme.park:APPNAME
# If docker socket volume needed, use below instead of mounting volume and also attach to socket network as well
#      DOCKER_HOST: tcp://dockersocket:2375
    labels:
      traefik.enable: true
      traefik.http.routers.APPNAME.rule: Host(`APPNAME.$DOMAIN`)
      traefik.http.routers.APPNAME.tls: true      
      traefik.http.routers.APPNAME.entryPoints: https
      traefik.http.routers.APPNAME.middlewares: oauth@file      
      traefik.http.routers.APPNAME.service: APPNAME
      traefik.http.services.APPNAME.loadbalancer.server.port: 80

networks:
  proxy:
    external: true
  socket:
    external: true
  internal: 
    external: true