version: '3.5'

services:
  
  APPNAME:
    image:
    container_name: APPNAME
    restart: unless-stopped
    env_file: APPNAME.env  
    security_opt:
      - no-new-privileges:true
    volumes:
      - $PWD:/config
      - $MEDIA:$MEDIA
      - $USENET:$USENET
      - $TORRENTS:$TORRENTS
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
#     Theme.Park.dev {Requires linuxserver.io containers}       
#      TP_THEME: ${THEME} # change in global.env file for global theme changes
#      DOCKER_MODS: ghcr.io/gilbn/theme.park:APPNAME
# If docker socket volume needed, use below instead of mounting volume and also attach to socket network as well
#      DOCKER_HOST: dockersocket
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.rule: Host(`audible.$DOMAIN`)
      traefik.http.routers.audiobookshelf.tls: true      
      traefik.http.routers.audiobookshelf.entryPoints: https
      traefik.http.routers.audiobookshelf.middlewares: oauth@file      
      traefik.http.routers.audiobookshelf.service: audiobookshelf
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
    networks:
      proxy:

networks:
  proxy:
    external: true
  socket:
    external: true
  internal: 
    external: true