#  Add 4K Banners to Posters in Plex + Tag 4K content with label and restrict sharing the label. 
#  Can have 4K and non-4K in same library

services:
  
  plexutils:
    image:  jkirkcaldy/plex-utills
    container_name: plexutils
    hostname: plexutils
    restart: unless-stopped
    networks: ["proxy"]      
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./logs:/logs
      - ./config:/config
      - $MEDIA:$MEDIA
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
    labels:
      traefik.enable: true
      traefik.http.routers.plexutils.rule: Host(`plexutils.$DOMAIN`)
      traefik.http.routers.plexutils.tls: true      
      traefik.http.routers.plexutils.entryPoints: https
      traefik.http.routers.plexutils.middlewares: oauth@file      
      traefik.http.routers.plexutils.service: plexutils
      traefik.http.services.plexutils.loadbalancer.server.port: 80

networks:
  proxy:
    external: true