#
#
#
services:
  
  prowlarr:
    image:  lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID    
      TP_THEME: $THEME
      DOCKER_MODS: ghcr.io/gilbn/theme.park:prowlarr
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.$DOMAIN`)
      traefik.http.routers.prowlarr.tls: true      
      traefik.http.routers.prowlarr.entryPoints: https
      traefik.http.routers.prowlarr.middlewares: oauth@file      
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
    networks:
      proxy:

networks:
  proxy:
    external: true