
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    networks: ["proxy"]      
    security_opt:
      - no-new-privileges:true
#    devices:
#      - /dev/dri:/dev/dri # Requires Plex Pass
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
        mode: host
    volumes:
      - ./config:/config
      - $MEDIA:$MEDIA  
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      TP_THEME: ${THEME}
      TP_ADDON: overseerr-side-menu
      DOCKER_MODS: ghcr.io/gilbn/theme.park:plex
      VERSION: docker
      PLEX_CLAIM: $PLEXTOKEN
      ADVERTISE_IP: http://plex.$DOMAIN
    labels:
      traefik.enable: true
      traefik.http.routers.plex.rule: Host(`plex.$DOMAIN`)
      traefik.http.routers.plex.tls: true      
      traefik.http.routers.plex.entryPoints: https     
      traefik.http.routers.plex.service: plex
      traefik.http.services.plex.loadbalancer.server.port: 32400

networks:
  proxy:
    external: true      
