
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/dri:/dev/dri # Requires Plex Pass
    ports:
      - 32400:32400 
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./config:/config
      - $MEDIA:$MEDIA  
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      TP_THEME: ${THEME}
      DOCKER_MODS: ghcr.io/gilbn/theme.park:plex
      VERSION: docker
      PLEX_CLAIM: $PLEXTOKEN
    labels:
      traefik.enable: true
      traefik.http.routers.plex.rule: Host(`plex.$DOMAIN`)
      traefik.http.routers.plex.tls: true      
      traefik.http.routers.plex.entryPoints: https     
      traefik.http.routers.plex.service: plex
      traefik.http.services.plex.loadbalancer.server.port: 32400
    networks:
      proxy:

networks:
  proxy:
    external: true      
