#
# 4K Sonarr Instance
#
services:
  
  sonar:
    image: randomninjaatk/sonarr-extended:latest
    container_name: sonar
    hostname: sonar
    restart: unless-stopped
    networks: ["proxy"]      
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK   
      TP_THEME: $THEME
      TP_ADDON: sonarr-4k-text-logo
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
      enableAutoConfig: true
      enableRecyclarr: true
      enableQueueCleaner: true
      enableExtras: true
      extrasType: all
      extrasLanguages: en-US
      extrasOfficialOnly: false
      extrasSingle: false
      extrasKodiCompatibility: false
      plexUrl: http://plex:32400
      plexToken: $PLEXTOKEN     
    labels:
      traefik.enable: true
      traefik.http.routers.sonar.rule: Host(`sonar.$DOMAIN`)
      traefik.http.routers.sonar.tls: true      
      traefik.http.routers.sonar.entryPoints: https
      traefik.http.routers.sonar.middlewares: oauth@file      
      traefik.http.routers.sonar.service: sonar
      traefik.http.services.sonar.loadbalancer.server.port: 8989

networks:
  proxy:
    external: true