version: "3.9"

services:

  autoscan:
    image: cloudb0x/autoscan:master
    container_name: autoscan
    restart: unless-stopped    
    volumes:
      - ./config:/config:rw
      - ../plex:/data/plex:ro
      - /etc/locatime:/etc/localtime:ro
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      AUTOSCAN_VERBOSITY: 0      
    labels:
      traefik.enable: true
      traefik.http.routers.autoscan.entrypoints: https
      traefik.http.routers.autoscan.rule: "Host(`autoscan.${DOMAIN}`)"
      traefik.http.routers.autoscan.tls: true
      traefik.http.routers.autoscan.middlewares: oauth@file
      traefik.http.routers.autoscan.service: autoscan      
      traefik.http.services.autoscan.loadbalancer.server.port: 3030
    networks:
      proxy:      

networks:
  proxy:
    external: true