#
# OliveTin gives safe and simple access to predefined shell commands from a web interface.
# https://github.com/OliveTin/OliveTin

services:

  olivetin:
    image: jamesread/olivetin  
    container_name: olivetin
    hostname: olivetin
    restart: unless-stopped
    networks: ["proxy"]      
    security_opt:
      - no-new-privileges:true    
    user: root
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.olivetin.rule: Host(`olive.$DOMAIN`)
      traefik.http.routers.olivetin.tls: true      
      traefik.http.routers.olivetin.entryPoints: https
      traefik.http.routers.olivetin.middlewares: oauth@file      
      traefik.http.routers.olivetin.service: olivetin
      traefik.http.services.olivetin.loadbalancer.server.port: 1337

networks:
  proxy:
    external: true