#
#
#
services:

  dockersocket:
    image: tecnativa/docker-socket-proxy  
    container_name: dockersocket
    hostname: dockersocket
    restart: unless-stopped
    networks: ["socket"]      
    privileged: true        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
#     debug|info|notice|warning|err|crit|alert|emerg
#     0 to revoke access | 1 to grant access.    
      LOG_LEVEL: info
      EVENTS: 1
      PING: 1
      VERSION: 1
      AUTH: 0
      SECRETS: 0
      POST: 1
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1
      DISTRIBUTION: 0
      EXEC: 0
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      NODES: 0
      PLUGINS: 0
      SERVICES: 1
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 1
      VOLUMES: 1

  dockergc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: dockergc
    hostname: dockergc
    restart: unless-stopped
    networks: ["socket"]    
    security_opt:
      - no-new-privileges:true   
    volumes:
      - ./docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      CRON: 0 0 0 * * ? # Everyday at midnight. Previously 0 0 * * *
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
      TZ: $TZ
      DOCKER_HOST: tcp://dockersocket:2375

networks:
  socket:
    external: true      