#
#
#

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
    environment: 
      APACHE_PORT: 11000 
      APACHE_IP_BINDING: 127.0.0.1 
      DOCKER_SOCKET_PATH: tcp://dockersocket:2375
      NEXTCLOUD_MOUNT: /storage/nextcloud
      NEXTCLOUD_DATADIR: /data/nextcloud
      SKIP_DOMAIN_VALIDATION: true
      TRUSTED_PROXIES: 172.24.0.0/16 # need to get subnet of proxy network or assign one when creating network. 
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.$DOMAIN       
    networks:
      proxy:

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer      