#
# OpenAudible Docker Container for Downloading Audible Library
#

services:
  
  openaudible:
    image: openaudible/openaudible:latest
    container_name: openaudible
    hostname: openaudible
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
      - $MEDIA:$MEDIA
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      traefik.enable: true
      traefik.http.routers.openaudible.rule: Host(`openaudible.$DOMAIN`)
      traefik.http.routers.openaudible.tls: true      
      traefik.http.routers.openaudible.entryPoints: https
      traefik.http.routers.openaudible.middlewares: oauth@file      
      traefik.http.routers.openaudible.service: openaudible
      traefik.http.services.openaudible.loadbalancer.server.port: 3000
    networks:
      proxy:

networks:
  proxy:
    external: true