#
#  FlexGet is a multipurpose automation tool for all of your media
#  https://flexget.com/
#

services:

  flexget:
    image: wiserain/flexget
    container_name: flexget
    hostname: flexget
    restart: unless-stopped
    volumes:
      - ./config:/config
      - $TORRENTS:$TORRENTS              
    environment:
      TZ: $TZ
      PGID: $PGID
      PUID: $PUID
    labels:
      traefik.enable: true
      traefik.http.routers.flexget.rule: Host(`flex.$DOMAIN`)
      traefik.http.routers.flexget.tls: true      
      traefik.http.routers.flexget.entryPoints: https
      traefik.http.routers.flexget.middlewares: oauth@file      
      traefik.http.routers.flexget.service: flexget
      traefik.http.services.flexget.loadbalancer.server.port: 5050
    networks:
      proxy:

networks:
  proxy:
    external: true      
