version: '3.5'

services:

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped    
    volumes:
      - ./config:/config
      - /storage:/storage
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: linuxserver/calibre-web:calibre      
    labels:
      traefik.enable: true
      traefik.http.routers.calibre.tls: true
      traefik.http.routers.calibre.entrypoints: https      
      traefik.http.routers.calibre.rule: Host(`books.$DOMAIN`)
      traefik.http.middlewares.calibre-headers.headers.customrequestheaders.X-Scheme: https
      traefik.http.routers.calibre.middlewares: calibre-headers
      traefik.http.routers.calibre.service: calibre
      traefik.http.services.calibre.loadbalancer.server.port: 8083
    networks:
      proxy:      

networks:
  proxy:
    external: true