version: "3.5"

services:

  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
#    env_file: firefly.env    # Can uncomment for smtp/mail or if need logs to debug
    depends_on:
      - firefly-db    
    security_opt:
      - no-new-privileges:true    
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      TRUSTED_PROXIES: "**"
      SITE_OWNER: $EMAIL       
      TZ: $TZ     
      DB_CONNECTION: mysql
      DB_HOST: firefly-db
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: $DB_USER
      DB_PASSWORD: $DB_PASS   
      APP_URL: https://budget.$DOMAIN
      APP_KEY: HARDOUTHEREFORAPIMPTRYINMAKERENT #32 character randomness
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: firefly-redis
    labels:
      traefik.enable: true
      traefik.http.routers.firefly.rule: Host(`budget.$DOMAIN`)
      traefik.http.routers.firefly.tls: true      
      traefik.http.routers.firefly.entryPoints: https
      traefik.http.routers.firefly.middlewares: oauth@file      
      traefik.http.routers.firefly.service: firefly
      traefik.http.services.firefly.loadbalancer.server.port: 8080          
    networks:
      internal:
      proxy:

  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
#    env_file: firefly.env  # Can uncomment for smtp/mail or if need logs to debug
    depends_on:
      - firefly
    environment:
      TZ: $TZ
      FIREFLY_III_URL: http://firefly:8080
      VANITY_URL: https://budget.$DOMAIN
      APP_NAME: DataImporter
      REDIS_HOST: firefly-redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      REDIS_DB: "0"
      REDIS_CACHE_DB: "1"
      TRUSTED_PROXIES: "**"
# Import directory white list. You need to set this before the auto importer will accept a directory to import from.
#      IMPORT_DIR_WHITELIST: 
# Create a Personal Access Token on the /profile page (at the bottom). Not command line token or APP_KEY.
#      FIREFLY_III_ACCESS_TOKEN:
    labels:
      traefik.enable: true
      traefik.http.routers.fidi.rule: Host(`fidi.$DOMAIN`)
      traefik.http.routers.fidi.tls: true      
      traefik.http.routers.fidi.entryPoints: https
      traefik.http.routers.fidi.middlewares: oauth@file      
      traefik.http.routers.fidi.service: fidi
      traefik.http.services.fidi.loadbalancer.server.port: 8080          
    networks:
      internal:
      proxy:  

  firefly-db:
    image: linuxserver/mariadb:10.6.10
    container_name: firefly-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      MYSQL_USER: $DB_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: firefly
    networks:
      internal:

  firefly-redis:
    image: redis  
    container_name: firefly-redis
    volumes:
      - ./redis:/data  
    networks:
      internal:

networks:
  proxy:
    external: true
  internal:
    external: true