version: '3.5'

services:

  ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: ddns
    restart: always
    env_file: cloudflare.env      
    environment:
      ZONE: $DOMAIN
      PROXIED: true
      RRTYPE: A
      DELETE_ON_STOP: false
      DNS_SERVER: 1.1.1.1
    networks:
      internal:

  cloudflare:
    image: tiredofit/traefik-cloudflare-companion:latest  
    container_name: cloudflare
    restart: always       
    env_file: cloudflare.env
    security_opt:
      - no-new-privileges:true   
    environment:
      TIMEZONE: $TZ
      TRAEFIK_VERSION: 2
      TARGET_DOMAIN: $DOMAIN
      DOMAIN1: $DOMAIN
      DOMAIN1_PROXIED: true
      DEFAULT_TTL: 1
      REFRESH_ENTRIES: true
      DOCKER_ENTRYPOINT: tcp://dockersocket:2375
      SWARM_MODE: false
    labels:  
#     For Non-Docker/Host Apps
      traefik.http.routers.cloudflare.rule: HostHeader(`admin.$DOMAIN`) || HostHeader(`vscode.$DOMAIN`)"
    networks:
      proxy:
      socket: 

networks:
  proxy:
    external: true
  socket:
    external: true 
  internal:
    external: true       