#
# View logs of Docker Containers
#

services:
  
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      DOCKER_HOST: tcp://dockersocket:2375
    labels:
      traefik.enable: true  
      traefik.http.routers.dozzle.entryPoints: https
      traefik.http.routers.dozzle.tls: true
      traefik.http.routers.dozzle.rule: Host(`logs.$DOMAIN`)            
      traefik.http.routers.dozzle.service: dozzle
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
    networks:
      proxy:
      socket:

networks:
  proxy:
    external: true
  socket:
    external: true