
services:

  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss    
    hostname: freshrss
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config        
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
    labels:
      traefik.enable: true
      traefik.http.routers.freshrss.rule: Host(`freshrss.$DOMAIN`)
      traefik.http.routers.freshrss.tls: true      
      traefik.http.routers.freshrss.entryPoints: https
      traefik.http.routers.freshrss.middlewares: oauth@file      
      traefik.http.routers.freshrss.service: freshrss
      traefik.http.services.freshrss.loadbalancer.server.port: 80
    networks:
      proxy:

networks:
  proxy:
    external: true