#
# Nabarr monitors Newznab/Torznab RSS feeds to find new media to add to Sonarr and or Radarr.
#  !!!!! Need to configure config.yml file. !!!!!!

services:

  nabarr:
    image: cloudb0x/nabarr:latest
    container_name: nabarr
    hostname: nabarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      APP_VERBOSITY: 0 # The Nabarr logging verbosity level to use. (0 = info, 1 = debug, 2 = trace)
    networks:
      internal:

networks:
  internal:
    external: true    