---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: My App

#background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
backgroundOpacity: 0.5

headerStyle: boxed  
theme: dark # or light

layout:
  Downloaders:
    style: row
    columns: 2
  Media:
    style: row
    columns: 4
  Arr's:
    style: row
    columns: 3
  Utilities:
    style: row
    columns: 5
  Network:
    style: row
    columns: 3    